version: '3'
services:
  db:
    container_name: dojo-postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres-password-here
    expose:
      - "5432"
  app:
    container_name: dojo-rails
    image: dojo
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    expose:
      - "3000"
    depends_on:
     - db
  web:
    container_name: dojo-nginx
    image: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    ports:
      - "80:80"
